## Settings
title: Ralihe R. Villagrán
description: 'Postdoctoral researcher in Mathematics, Eindhoven University of Technology'
url: https://ralihemath.github.io
baseurl: '/'
encoding: UTF-8

google_analytics: 'UA-174550874-1'
## disqus_shortname: ''

author:
  name: 'Ralihe R. Villagrán'
  email: ralihemath@gmail.com
  twitter_username: RaLiHe
  github_username:  Ralihe

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

## Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
